class Resource {
    int getValue()
}

class Brick {
}

class Food {
}

class Tool {
}

class Wine {
}

class Cloth {
}

class Resource <|- Brick
class Resource <|- Food
class Resource <|- Tool
class Resource <|- Wine
class Resource <|- Cloth


enum CityGroup {
  A
  B
  C
  D
}

enum Region {
  City[] cities
}

class City {
  String name
  CityGroup group
  Resource resource
  Road[] roads
}

class Road {
  City[2] cities
  bool isPlayerIn
}

class Region *-- City
class City *-- CityGroup

enum God {
  VESTA
  JUPITER
  SATURNUS
  MERCURIUS
  MARS
  MINERVA
}

Enum CardType {
  TRIBUNE
  ARCHITECT
  PREFECT
  COLONIST
  MERCATOR
  DIPLOMAT
  SENATOR
  CONSUL
  MASON
  FARMER
  SMITH
  VINTER
  WEAVER
}

class Card {
  God god
  CardType type
}

class Card *-- God
class Card *-- CardType
