class resource {
    getValue() : int
}

class Brick {
}

class Food {
}

class Tool {
}

class Wine {
}

class Cloth {
}

class resource <|- Brick
class resource <|- Food
class resource <|- Tool
class resource <|- Wine
class resource <|- Cloth
